### Name-Pratyoosh Anand
### Batch-B4

In [1]:
import numpy as np

1.	How to add a border around a NumPy array?

In [2]:
x=np.ones((3,3))
print("Without border matrix")
print(x)
x = np.pad(x, pad_width=1, mode='constant',
               constant_values=0)
print("Border Matrix")
print(x)

Without border matrix
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Border Matrix
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


How to compare two NumPy arrays?

In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
np.equal(x,y)

array([[ True,  True],
       [ True,  True]])

How to check whether specified values are present in NumPy array?

In [4]:
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])
print(2 in n_array)

True


How to get all 2D diagonals of a 3D NumPy array?

In [5]:
x = np.arange(3 * 3 * 4).reshape(3, 3, 4)
  
print("Original 3d array:\n", 
      x)
  
# Create 2D diagonal array
diag_x = np.diagonal(x, 
                       axis1 = 1,
                       axis2 = 2)
  
print("2d diagonal array:\n",
      diag_x)

Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
2d diagonal array:
 [[ 0  5 10]
 [12 17 22]
 [24 29 34]]


Flatten a Matrix in Python using NumPy

In [6]:
arr = np.array([[2, 4], [4, 5]])
  
# using array.flatten() method
flat_arr = arr.flatten()
print(flat_arr)

[2 4 4 5]


Flatten a 2d numpy array into 1d array

In [7]:
prim_arr=np.array([[1,2],[2,3],[3,4]])
print(prim_arr)
print("1d array")
print(prim_arr.flatten())

[[1 2]
 [2 3]
 [3 4]]
1d array
[1 2 2 3 3 4]


How to Calculate the determinant of a matrix using NumPy?

In [8]:
arr=np.array([[25,24],[45,43]])
print("Determinant")
print(np.linalg.det(arr))

Determinant
-4.999999999999952


How to inverse a matrix using NumPy

In [9]:
arr=np.array([[2,4,6],[4,6,7],[4,5,6]])
print("Matrix\n")
print(arr)
print("Inverse\n")
print(np.linalg.inv(arr))

Matrix

[[2 4 6]
 [4 6 7]
 [4 5 6]]
Inverse

[[-0.16666667 -1.          1.33333333]
 [-0.66666667  2.         -1.66666667]
 [ 0.66666667 -1.          0.66666667]]


How to count the frequency of unique values in NumPy array?


In [10]:
arr=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(np.unique(arr))

[1 2 3]


Multiply matrices of complex numbers using NumPy in Python

In [11]:
arr1=np.array([1+3j,4+5j])
arr2=np.array([1+2j,3j])
print(np.vdot(arr1,arr2))

(22+11j)


Compute the outer product of two given vectors using NumPy in Python

In [12]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[1,3],[2,4]])
print(np.outer(arr1,arr2))

[[ 1  3  2  4]
 [ 2  6  4  8]
 [ 2  6  4  8]
 [ 3  9  6 12]]


Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [13]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[1,3],[2,4]])
print("Inner")
print(np.inner(arr1,arr2))
print("Outer")
print(np.outer(arr1,arr2))
print("Cross")
print(np.cross(arr1,arr2))

Inner
[[ 7 10]
 [11 16]]
Outer
[[ 1  3  2  4]
 [ 2  6  4  8]
 [ 2  6  4  8]
 [ 3  9  6 12]]
Cross
[1 2]


Compute the covariance matrix of two given NumPy arrays

In [14]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[1,3],[2,4]])
print(np.cov(arr1,arr2))

[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


Compute the Kronecker product of two mulitdimension NumPy arrays

In [15]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[1,3],[2,4]])
print(np.kron(arr1,arr2))

[[ 1  3  2  6]
 [ 2  4  4  8]
 [ 2  6  3  9]
 [ 4  8  6 12]]


Python | Numpy matrix.tolist()

In [16]:
arr1=np.array([[1,2],[2,3]])
print(arr1.tolist())

[[1, 2], [2, 3]]


Find indices of elements equal to zero in a NumPy array

In [17]:
n_array = np.array([1, 0, 2, 0, 3, 0, 0, 5,
                    6, 7, 5, 0, 8])
res = np.where(n_array == 0)[0]
print(res)

[ 1  3  5  6 11]


How to Remove columns in Numpy array that contains non-numeric values?

In [18]:
n_arr = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, np.nan]])
print(n_arr[:, ~np.isnan(n_arr).any(axis=0)])

[[10.5 22.5]
 [41.  52.5]]


How to access different rows of a multidimensional NumPy array?

In [19]:
arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]])
  
# Access the First and Last rows of array
res_arr = arr[[0,2]]
print(res_arr)

[[10 20 30]
 [70 88 94]]


Python | numpy.fill_diagonal() method

In [20]:
array = np.zeros((3, 3), int)
np.fill_diagonal(array, 1)
  
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Python | numpy.isin() method

In [21]:
arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]])
print(np.isin(arr,[10,20,30]))

[[ True  True  True]
 [False False False]
 [False False False]]


Combined array index by index

In [22]:
gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])
print(np.dstack((gfg1, gfg2)))

[[[1 4]
  [2 5]
  [3 6]]]


Calculate the Euclidean distance using NumPy

In [23]:
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))
print(np.linalg.norm(point1 - point2))

2.23606797749979


Sort the values in a matrix

In [24]:
arr=np.array([12,4,5,8,21,23])
print(np.sort(arr))

[ 4  5  8 12 21 23]


Filter out integers from float numpy array

In [25]:
arr=np.array([0.5,1.0,2.0,3.5,4.0,4.5])
arr_result=arr[arr==arr.astype(int)]
print(arr_result)

[1. 2. 4.]


Find the indices into a sorted array

In [26]:
arr=np.array([12,4,5,8,21,23])
print(np.searchsorted(arr,8))

3


Calculate the sum of all columns in a 2D NumPy array

In [27]:
def colsum(arr, n, m):
    for i in range(n):
        su = 0;
        for j in range(m):
            su += arr[j][i]
        print(su, end = " ")   
 
# creating the 2D Array
TwoDList = [[1, 2, 3], [4, 5, 6],
            [7, 8, 9], [10, 11, 12]]
TwoDArray = np.array(TwoDList)
 
# displaying the 2D Array
print("2D Array:")
print(TwoDArray)
 
# printing the sum of each column
print("\nColumn-wise Sum:")
colsum(TwoDArray, len(TwoDArray[0]), len(TwoDArray))

2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Column-wise Sum:
22 26 30 

	Calculate average values of two given NumPy arrays

In [28]:
arr1=np.array([3,4])
arr2=np.array([4,5])
avg=(arr1+arr2)/2
print(avg)

[3.5 4.5]


How to compute numerical negative value for all elements in a given NumPy array?

In [30]:
arr1=np.array([1,2,-1,-2,3,4,-5,6])
x=np.negative(arr1)
print(x)

[-1 -2  1  2 -3 -4  5 -6]


How to get the floor, ceiling and truncated values of the elements of a numpy array?

In [32]:
x=np.array([1.2])
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[1.]
[2.]
[1.]


How to round elements of the NumPy array to the nearest integer?

In [33]:
y=np.array([0.2,0.3,1.2,0.5,1.5])
print(np.rint(y))

[0. 0. 1. 0. 2.]


Find the round off the values of the given matrix

In [34]:
a=np.array([0.2,1,1.2])
print(a.round())

[0. 1. 1.]


In [35]:
arr=np.array([4])
print(np.sqrt(arr))

[2.]


Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

In [36]:
matrix1 = np.array([[1, 2], [0, 2]])
matrix2 = np.array([[0, 1], [3, 4]])
print(np.einsum("mk,kn", matrix1, matrix2))

[[6 9]
 [6 8]]


numpy.std() in Python

In [37]:
arr=np.array([1,2,3,4,5,6])
print(np.std(arr))

1.707825127659933


Compute pearson product-moment correlation coefficients of two given NumPy arrays

In [38]:
array1 = np.array([0, 1, 2])
array2 = np.array([3, 4, 5])
print(np.corrcoef(array1,array2))

[[1. 1.]
 [1. 1.]]


Calculate the mean across dimension in a 2D NumPy array

In [39]:
arr1=np.array([[1,2],[3,4]])
np.mean(arr1)

2.5

Calculate the average, variance and standard deviation in Python using NumPy

In [41]:
import numpy as np
list = [2, 4, 4, 4, 5, 5, 7, 9]
print(np.average(list))
print(np.var(list))
print(np.std(list))

5.0
4.0
2.0


Describe a NumPy Array in Python

In [42]:
arr=np.array([1,2,3,4,5,6,6])
print(np.mean(arr))
print(np.median(arr))

3.857142857142857
4.0


How to divide a polynomial to another using NumPy in Python?

In [43]:

px = (5, -2, 5)
gx = (2, 1, 0)
  
# divide the polynomials
qx, rx = np.polynomial.polynomial.polydiv(px, gx)
  
# print the result
# quotiient
print(qx)
  
# remainder
print(rx)

[-12.   5.]
[29.]


Find the roots of the polynomials using NumPy

In [44]:
coef=np.array([1,2,2])
np.roots(coef)

array([-1.+1.j, -1.-1.j])

Python | Numpy np.polygrid2d() method

numpy string operations | upper() function

In [45]:
input_arr=np.array(['gef','f','go','oyl'])
np.char.upper(input_arr)

array(['GEF', 'F', 'GO', 'OYL'], dtype='<U3')

numpy string operations | lower() function

In [46]:
input_arr=np.array(['GEF', 'F', 'GO', 'OYL'])
np.char.lower(input_arr)

array(['gef', 'f', 'go', 'oyl'], dtype='<U3')

numpy string operations | join() function

In [47]:
input_arr=np.array(['PYThon'])
sep=np.array('-')
np.core.defchararray.join(sep, input_arr)

array(['P-Y-T-h-o-n'], dtype='<U11')

numpy string operations | not_equal() function

In [50]:
arr1=np.array("hello")
arr2=np.array("hell")
print(np.char.not_equal(arr1,arr2))

True


numpy string operations | count() function

In [52]:
import numpy as np
  
# input arrays  
in_arr = np.array(['Sayantan', '  Sayan  ', 'Sayansubhra'])
print ("Input array : ", input_arr) 
  
# output arrays 
output_arr = np.char.count(in_arr, sub ='an')
print ("Output array: ", output_arr) 

Input array :  ['PYThon']
Output array:  [2 1 1]


numpy string operations | find() function

In [55]:

# input arrays  
input_arr = np.array(['aAaAaA', 'baA', 'abBABba'])
print ("Input array : ", input_arr) 
  
# output arrays 
output_arr = np.char.find(in_arr, sub ='A')
print ("Output array: ", output_arr) 

Input array :  ['aAaAaA' 'baA' 'abBABba']
Output array:  [-1 -1 -1]


Python | Numpy np.char.endswith() method

In [58]:
arr = np.array(['geeks', 'for', 'geeks'])
gfg = np.char.endswith(arr, 'ks')
  
print(gfg)

[ True False  True]
